### ISSUE TITLE
Azure DevOps [PublishTestResult] attachments paths

### ISSUE THREAD

**Issue by NilsEngelbach** [NickLargen/testcafe-reporter-nunit3#5]
Should it be possible to publish the test attachments with a relative path in Azure DevOps for NUnit3 reports created with the testcafe-reporter-nunit3 reporter?

The task is configured like this:

```yml
- task: PublishTestResult@2
   inputs:
     testResultsFormat: 'NUnit'
     testResultsFiles: 'tmp/report.xml'
     publishRunAttachments: true
```

The report looks like this:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<test-run>
    <test-suite type="Assembly" name="...">
        <-- ... -->
        <test-case name="..." result="Failed" duration="24.161">
            <failure>
                <message>
                    ...
                </message>
                <stack-trace>
                    ...
                </stack-trace>
            </failure>
            <attachments>
                <attachment>
                    <filePath>tmp/screenshots/.../errors/1.png</filePath>
                </attachment>
            </attachments>
        </test-case>
    </test-suite>
</test-run>
```

It seems that the file can not be found, even tough it is in the given location relative to $(System.DefaultWorkingDirectory):

```
##[warning]Skipping attachment as it is not available on disk: tmp/screenshots/.../errors/1.png
```

Should attachment path be absolute? I also tried running it on linux and windows build agents.
